### ISSUE TITLE
not working properly

### ISSUE THREAD

**Issue by mrjason1000** [Tajam/jext-spigot-plugin#11]
logs:
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.isSet(String)" because "section" is null
[03:33:19 WARN]: 	at JukeboxExtended-1.2.1.jar//me.tajam.jext.config.field.ConfigField.updateData(ConfigField.java:26)
[03:33:19 WARN]: 	at JukeboxExtended-1.2.1.jar//me.tajam.jext.config.ConfigDiscData.load(ConfigDiscData.java:51)
[03:33:19 WARN]: 	at JukeboxExtended-1.2.1.jar//me.tajam.jext.config.ConfigDiscManager.load(ConfigDiscManager.java:33)
[03:33:19 WARN]: 	at JukeboxExtended-1.2.1.jar//me.tajam.jext.config.ConfigManager.load(ConfigManager.java:51)
[03:33:19 WARN]: 	at JukeboxExtended-1.2.1.jar//me.tajam.jext.Jext.load(Jext.java:38)
[03:33:19 WARN]: 	at JukeboxExtended-1.2.1.jar//me.tajam.jext.Jext.onEnable(Jext.java:19)
[03:33:19 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[03:33:19 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[03:33:19 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[03:33:19 WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[03:33:19 WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[03:33:19 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664)
[03:33:19 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[03:33:19 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[03:33:19 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
[03:33:19 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[03:33:19 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by mrjason1000** [comment]
i have latest version of protocolib
